
#ifndef MPCPATHFOLLOWING_3V_1_CASADI_H
#define MPCPATHFOLLOWING_3V_1_CASADI_H

/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef real_t
#define real_t double
#define to_double(x) (double) x
#define to_int(x) (int) x
#endif /* real_t */

int MPCPathFollowing_3v_1_objective_1(const real_t** arg, real_t** res, int* iw, real_t* w);

int MPCPathFollowing_3v_1_objective_1_sparsity(int i, int *nrow, int *ncol, const int **colind, const int **row);

int MPCPathFollowing_3v_1_dynamics_1(const real_t** arg, real_t** res, int* iw, real_t* w);

int MPCPathFollowing_3v_1_dynamics_1_sparsity(int i, int *nrow, int *ncol, const int **colind, const int **row);

int MPCPathFollowing_3v_1_inequalities_1(const real_t** arg, real_t** res, int* iw, real_t* w);

int MPCPathFollowing_3v_1_inequalities_1_sparsity(int i, int *nrow, int *ncol, const int **colind, const int **row);

int MPCPathFollowing_3v_1_objective_60(const real_t** arg, real_t** res, int* iw, real_t* w);

int MPCPathFollowing_3v_1_objective_60_sparsity(int i, int *nrow, int *ncol, const int **colind, const int **row);

int MPCPathFollowing_3v_1_inequalities_60(const real_t** arg, real_t** res, int* iw, real_t* w);

int MPCPathFollowing_3v_1_inequalities_60_sparsity(int i, int *nrow, int *ncol, const int **colind, const int **row);

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif
